FROM pytorch/pytorch:latest
RUN  apt-get -y update && apt-get -y upgrade
RUN  apt-get -y install git ffmpeg libsm6 libxext6 wget
COPY requirements.txt /requirements.txt
RUN  python3 -m pip install --upgrade pip --no-cache-dir --root-user-action=ignore
RUN  python3 -m pip install -r /requirements.txt --no-cache-dir --root-user-action=ignore
RUN  python3 -m pip install git+https://github.com/facebookresearch/segment-anything.git
WORKDIR /torch
CMD jupyter notebook --notebook-dir=/torch/notebooks --ip=0.0.0.0 --port=9999 --no-browser --allow-root